Update EndTestAuto.yml

diff --git a/.github/workflows/EndTestAuto.yml b/.github/workflows/EndTestAuto.yml
--- a/.github/workflows/EndTestAuto.yml
+++ b/.github/workflows/EndTestAuto.yml
@@ -40,8 +40,9 @@ jobs:
   Check_test_results:
     name: Reviews test case results and check for issues
     needs: run_test_case
-      if: ${steps.endtest_functional_tests.outputs.failed} != 0
-      steps:
-        run: |
-          echo "There was at least 1 test case that failed"
-          exit 1
+      echo: run_test_case.failed 
+    #  if: ${steps.endtest_functional_tests.outputs.failed} != 0
+    #  steps:
+    #    run: |
+    #      echo "There was at least 1 test case that failed"
+    #      exit 1
