Update EndTestAuto.yml

diff --git a/.github/workflows/EndTestAuto.yml b/.github/workflows/EndTestAuto.yml
--- a/.github/workflows/EndTestAuto.yml
+++ b/.github/workflows/EndTestAuto.yml
@@ -36,9 +36,10 @@ jobs:
           echo ${{ steps.endtest_functional_tests.outputs.screenshots_and_video }}
           echo ${{ steps.endtest_functional_tests.outputs.hash }}
           echo ${{ steps.endtest_functional_tests.outputs.results }}
-
-      - name: Check for failed test cases
-        if: $steps.endtest_functional_tests.outputs.failed != 0
-        run: |
-          echo "There was at least 1 test case that failed"
-          exit 1
+  
+job2:
+  script:
+      if: $steps.endtest_functional_tests.outputs.failed != 0
+      run: |
+        echo "There was at least 1 test case that failed"
+         exit 1
